# Generated by Django 2.1.15 on 2020-06-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_title', models.CharField(max_length=10)),
                ('my_content', models.TextField()),
                ('my_created_at', models.DateTimeField(auto_now_add=True)),
                ('my_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
