# Generated by Django 3.0.7 on 2020-06-26 04:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='accounts'),
        ),
    ]
